### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Mrkwtkr** [Malorolam/MalCore#1]
Could u add language support for the guidebook? (xx_XX.lang/XXX_xx_XX.xml)
That will be very helpful, thank u :D

**Comment by Mrkwtkr** [comment]
And the hyperlink of 'Malcore' on ur curse thread (http://www.curse.com/mc-mods/minecraft/223574-curse-cobalt-web-forms-textfield) should be http://www.curse.com/mc-mods/minecraft/223573-curse-cobalt-web-forms-textfield

**Comment by Malorolam** [comment]
Added to the todo for next version.

Thank you for the broken link report as well.

**Comment by Mrkwtkr** [comment]
About the book, u can take a look at those from Tinker's Construct,Thaumcraft, Flaxbeard's Steam Power, Botania, Mariculture, etc. :)

**Comment by Mrkwtkr** [comment]
Im so sorry:( It should be http://www.curse.com/mc-mods/minecraft/223573-malcore
Made a big mistake!

**Comment by Malorolam** [comment]
Alright, the link should be fixed now and I've added .lang support for the guidebook.
