### ISSUE TITLE
Crash Report with Patience loot bag (1.12.2)

### ISSUE THREAD

**Issue by WaffleTraits** [Malorolam/MalCore#2]
Ok so i had a patience loot bag in my offhand, when i right clicked with my main hand empty, a gui containing another patience loot bag showed up. I tried to to take it out but i immediately crashed. Keep in mind this was also on a multiplayer server so i dont know what other factors could affect it. We had to have the mod removed in order for me to not crash when i logged back on.

**Comment by Malorolam** [comment]
It'll be fixed in 2.5.3b

**Comment by WaffleTraits** [comment]
Awesome thanks man
